name: WakaTime Readme

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: wujihua118/wujihua118@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
